spring.application.name=Part29-SpringSecEx
#spring.security.user.name=navin
#spring.security.user.password=likhith

spring.datasource.url=jdbc:postgresql://localhost:5432/likhith
spring.datasource.username=postgres
spring.datasource.password=l@123

server.port = 8081


