spring.application.name=SpringSecEx
#spring.security.user.name=navin
#spring.security.user.password=likhith

spring.datasource.url=jdbc:postgresql://localhost:<DB_PORT>/likhith
spring.datasource.username=<YOUR_DB_USERNAME>
spring.datasource.password=<YOUR_DB_PASSWORD>

server.port = <BACKEND_PORT>


