spring.application.name=ecom-proj

spring.datasource.url=jdbc:postgresql://localhost:5432/likhith
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=<YOUR_DB_USERNAME>
spring.datasource.password=<YOUR_DB_PASSWORD>

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
